export default ['Banc',
  'banquette',
  'Bibliothèque',
  'buffet',
  'bureau',
  'canapé',
  'chaise',
  'chaise haute',
  'chariot bar',
  'étagère',
  'fauteuil',
  'luminaire',
  'miroir',
  'paravent',
  'patère et valet',
  "table basse et d'appoint",
  'table de repas'];
